# Week 2: SIG Data Science

Today we will be going over Data Science libraries for Python!

Data Analysis Tools: Numpy and Pandas

Data Visualization Tools: Matplotlib, Seaborn, Plotly, and Cufflinks

## Numpy

In [1]:
#Import Statement
import numpy as np

The fundamental data structure of numpy is known as the array (also known as numpy array)

In [7]:
lst = [1,2,3]

In [8]:
lst

[1, 2, 3]

In [5]:
arr = np.array(lst)

In [6]:
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [10]:
#Multiple Dimensions
arr1 = np.array([[1,2],[3,4]])

In [11]:
arr1

array([[1, 2],
       [3, 4]])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Grabs every number from the first to the last-1 and puts it in a numpy array

In [13]:
# Lets say we want every even number in the range from 0-10
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Third argument is the step size

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))
# Notice how it passes in a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# What if I want a numpy array of ten 5's?
# Hint: You can multiply an array by a scalar (essentially a single number)


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
# linspace has a start and stop and the number of elements in it (which are evenly spaced)
np.linspace(0,15,6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [24]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [28]:
# I want a numpy array from 0 to 11 (inclusive) with 6 elements


array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [32]:
# numpy's random library is used quite extensively
np.random.randint(0,10) # returns a single random integer between low and high-1

1

In [33]:
np.random.randint(0,100,10)

array([70, 63, 87, 75,  9, 77, 40,  4, 63, 40])

In [30]:
np.random.normal() # draw random samples from a NORMAL distribution

-1.4087387738143384

In [43]:
# Lets say we want to ensure that we all generate the same random numbers?
np.random.seed(101) # passed in number can be anything but it should be the same for all of us

#NOTE: seed and randint must be in the same cell
np.random.randint(0,15,5)

array([11,  1,  6,  7, 13])

In [44]:
np.random.randint(0,15,5)

array([11,  9, 13,  8,  4])

In [45]:
arr = np.random.randint(0,100,10)

In [46]:
arr

array([63, 40, 60, 92, 64,  5, 12, 93, 40, 49])

In [47]:
max(arr)

93

In [48]:
min(arr)

5

In [50]:
arr.mean()

51.8

In [51]:
arr.argmax()

7

In [52]:
arr.argmin()

5

In [54]:
# Grabs values from a normal distribution
np.random.randn(5)

array([-0.3653608 ,  2.42766622,  1.02335539,  0.56007451,  0.14005432])

In [55]:
len(arr)

10

In [56]:
# We can "reshape" this array to have multiple rows
arr.reshape(2,5)

array([[63, 40, 60, 92, 64],
       [ 5, 12, 93, 40, 49]])

In [57]:
mat = np.arange(0,100).reshape(10,10)

In [58]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
# Let's say i want the value from the first row, second column?
mat[0,1]

1

In [60]:
mat[4,3]

43

In [61]:
# we can use splicing to grab certain chunks

# i want the entire first column
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
# i want the entire first row
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# i want all elements in the first three rows and first three columns


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [66]:
# i want all elements from columns 3-5 and rows 4-6


array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [70]:
# all elements in the last three columns and last four rows


array([[67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])