# Week 2: SIG Data Science

Today we will be going over Data Science libraries for Python!

Data Analysis Tools: Numpy and Pandas

Data Visualization Tools: Matplotlib, Seaborn, Plotly, and Cufflinks

## Numpy

In [1]:
#Import Statement
import numpy as np

The fundamental data structure of numpy is known as the array (also known as numpy array)

In [2]:
lst = [1,2,3]

In [3]:
lst

[1, 2, 3]

In [4]:
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
#Multiple Dimensions
arr1 = np.array([[1,2],[3,4]])

In [8]:
arr1

array([[1, 2],
       [3, 4]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Grabs every number from the first to the last-1 and puts it in a numpy array

In [10]:
# Lets say we want every even number in the range from 0-10
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Third argument is the step size

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,5))
# Notice how it passes in a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# What if I want a numpy array of ten 5's?
# Hint: You can multiply an array by a scalar (essentially a single number)


In [16]:
# linspace has a start and stop and the number of elements in it (which are evenly spaced)
np.linspace(0,15,6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [17]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [18]:
# I want a numpy array from 0 to 11 (inclusive) with 6 elements


In [19]:
# numpy's random library is used quite extensively
np.random.randint(0,10) # returns a single random integer between low and high-1

6

In [20]:
np.random.randint(0,100,10)

array([11, 67, 87, 59, 76, 72,  0, 33, 29, 53])

In [21]:
np.random.normal() # draw random samples from a NORMAL distribution

-0.36260269845332765

In [22]:
# Lets say we want to ensure that we all generate the same random numbers?
np.random.seed(101) # passed in number can be anything but it should be the same for all of us

#NOTE: seed and randint must be in the same cell
np.random.randint(0,15,5)

array([11,  1,  6,  7, 13])

In [23]:
np.random.randint(0,15,5)

array([11,  9, 13,  8,  4])

In [24]:
arr = np.random.randint(0,100,10)

In [25]:
arr

array([63, 40, 60, 92, 64,  5, 12, 93, 40, 49])

In [26]:
max(arr)

93

In [27]:
min(arr)

5

In [28]:
arr.mean()

51.8

In [29]:
arr.argmax()

7

In [30]:
arr.argmin()

5

In [31]:
# Grabs values from a normal distribution
np.random.randn(5)

array([ 0.06947685, -0.3653608 ,  2.42766622,  1.02335539,  0.56007451])

In [32]:
len(arr)

10

In [33]:
# We can "reshape" this array to have multiple rows
arr.reshape(2,5)

array([[63, 40, 60, 92, 64],
       [ 5, 12, 93, 40, 49]])

In [34]:
mat = np.arange(0,100).reshape(10,10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
# Let's say i want the value from the first row, second column?
mat[0,1]

1

In [37]:
mat[4,3]

43

In [38]:
# we can use splicing to grab certain chunks

# i want the entire first column
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# i want the entire first row
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# i want all elements in the first three rows and first three columns


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [50]:
# i want all elements from columns 3-5 and rows 4-6


array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [51]:
# all elements in the last three columns and last four rows


array([[67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [44]:
# all elements greater than 50
my_filter = mat > 50
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Pandas

In [52]:
import pandas as pd