# Week 2: SIG Data Science

Today we will be going over Data Science libraries for Python!

Data Analysis Tools: Numpy and Pandas

Data Visualization Tools: Matplotlib, Seaborn, Plotly, and Cufflinks

## Numpy

In [17]:
#Import Statement
import numpy as np

The fundamental data structure of numpy is known as the array (also known as numpy array)

In [2]:
lst = [1,2,3]

In [3]:
lst

[1, 2, 3]

In [4]:
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
#Multiple Dimensions
arr1 = np.array([[1,2],[3,4]])

In [8]:
arr1

array([[1, 2],
       [3, 4]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Grabs every number from the first to the last-1 and puts it in a numpy array

In [10]:
# Lets say we want every even number in the range from 0-10
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Third argument is the step size

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,5))
# Notice how it passes in a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# What if I want a numpy array of ten 5's?
# Hint: You can multiply an array by a scalar (essentially a single number)


In [16]:
# linspace has a start and stop and the number of elements in it (which are evenly spaced)
np.linspace(0,15,6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [17]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [18]:
# I want a numpy array from 0 to 11 (inclusive) with 6 elements


In [19]:
# numpy's random library is used quite extensively
np.random.randint(0,10) # returns a single random integer between low and high-1

6

In [20]:
np.random.randint(0,100,10)

array([11, 67, 87, 59, 76, 72,  0, 33, 29, 53])

In [21]:
np.random.normal() # draw random samples from a NORMAL distribution

-0.36260269845332765

In [22]:
# Lets say we want to ensure that we all generate the same random numbers?
np.random.seed(101) # passed in number can be anything but it should be the same for all of us

#NOTE: seed and randint must be in the same cell
np.random.randint(0,15,5)

array([11,  1,  6,  7, 13])

In [23]:
np.random.randint(0,15,5)

array([11,  9, 13,  8,  4])

In [24]:
arr = np.random.randint(0,100,10)

In [25]:
arr

array([63, 40, 60, 92, 64,  5, 12, 93, 40, 49])

In [26]:
max(arr)

93

In [27]:
min(arr)

5

In [28]:
arr.mean()

51.8

In [29]:
arr.argmax()

7

In [30]:
arr.argmin()

5

In [31]:
# Grabs values from a normal distribution
np.random.randn(5)

array([ 0.06947685, -0.3653608 ,  2.42766622,  1.02335539,  0.56007451])

In [47]:
np.random.randn(20)

array([-0.35174275, -0.106265  ,  0.50314657, -2.70985998, -0.68508402,
       -1.29591138,  0.2904039 ,  0.16044775,  1.80063562, -0.23992473,
        0.00603984, -1.10509026, -0.40236267, -1.27257014,  0.80951392,
        1.38194042,  1.27164618, -1.63999788,  1.13934538, -2.32622041])

In [57]:
np.random.randn(2,5)

array([[ 0.50200835, -0.90487751, -1.26021736,  0.51414112, -0.28121328],
       [-1.96935595, -1.29990221,  1.11730135,  2.29141517,  0.03083171]])

In [33]:
# We can "reshape" this array to have multiple rows
arr.reshape(2,5)

array([[63, 40, 60, 92, 64],
       [ 5, 12, 93, 40, 49]])

In [34]:
mat = np.arange(0,100).reshape(10,10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
# Let's say i want the value from the first row, second column?
mat[0,1]

1

In [37]:
mat[4,3]

43

In [38]:
# we can use splicing to grab certain chunks

# i want the entire first column
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# i want the entire first row
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# i want all elements in the first three rows and first three columns


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [50]:
# i want all elements from columns 3-5 and rows 4-6


array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [51]:
# all elements in the last three columns and last four rows


array([[67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [44]:
# all elements greater than 50
my_filter = mat > 50
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Pandas

In [3]:
import pandas as pd

Series: A one dimensional data structure

DataFrame: 2-d data structure

In [4]:
d = {'a':10,'b':20,'c':30}

In [5]:
ser = pd.Series(d)

In [6]:
ser

a    10
b    20
c    30
dtype: int64

In [7]:
type(ser)

pandas.core.series.Series

In [8]:
lst = [1,2,3]

In [9]:
pd.Series(lst)

0    1
1    2
2    3
dtype: int64

In [10]:
labels = ['one','two','three']

In [12]:
pd.Series(data=lst,index=labels)

one      1
two      2
three    3
dtype: int64

In [13]:
pd.Series([1,2,3,4],['First', 'Second', 'Third', 'Fourth'])

First     1
Second    2
Third     3
Fourth    4
dtype: int64

In [14]:
ser1 = pd.Series(lst)

In [15]:
ser1[0]

1

In [22]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [23]:
df

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178
E  0.200822 -0.253019  0.097659  0.744367

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df['W']

A   -1.752179
B    0.187321
C    0.596200
D   -1.086823
E    0.200822
Name: W, dtype: float64

In [31]:
# Notice the .loc
df.loc['A']

W   -1.752179
X    0.328465
Y   -0.547127
Z   -0.136217
Name: A, dtype: float64

In [32]:
df[['W','Z']]

W         Z
A -1.752179 -0.136217
B  0.187321 -1.231558
C  0.596200  0.286677
D -1.086823 -0.643178
E  0.200822  0.744367

In [33]:
type(df['W'])

pandas.core.series.Series

In [35]:
type(df[['W','Z']])

pandas.core.frame.DataFrame

In [36]:
# what if I want to grab the element at row B, column Y?
df.loc['B','Y']

0.35181370278377844

In [37]:
df['new'] = df['W'] + df['Y']

In [38]:
df

W         X         Y         Z       new
A -1.752179  0.328465 -0.547127 -0.136217 -2.299306
B  0.187321  0.590627  0.351814 -1.231558  0.539134
C  0.596200 -1.571288  1.613763  0.286677  2.209963
D -1.086823  0.824722  2.166121 -0.643178  1.079298
E  0.200822 -0.253019  0.097659  0.744367  0.298480

In [39]:
df['new']

A   -2.299306
B    0.539134
C    2.209963
D    1.079298
E    0.298480
Name: new, dtype: float64

In [40]:
# Now I want to delete this newly created column
df.drop('new',axis=1)

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178
E  0.200822 -0.253019  0.097659  0.744367

In [41]:
df
# why is the new column still showing up after I already got rid of it??

W         X         Y         Z       new
A -1.752179  0.328465 -0.547127 -0.136217 -2.299306
B  0.187321  0.590627  0.351814 -1.231558  0.539134
C  0.596200 -1.571288  1.613763  0.286677  2.209963
D -1.086823  0.824722  2.166121 -0.643178  1.079298
E  0.200822 -0.253019  0.097659  0.744367  0.298480

In [42]:
df.drop('new',axis=1,inplace=True)

In [43]:
df
# need to add the inplace argument

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178
E  0.200822 -0.253019  0.097659  0.744367

In [44]:
df.drop('E')

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178

In [45]:
df
# i didn't set inplace to True so the E row is still there

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178
E  0.200822 -0.253019  0.097659  0.744367

In [58]:
# what if i want the elements in rows a,b and columns w,y?


W         Y
A -1.752179 -0.547127
B  0.187321  0.351814

In [59]:
df

W         X         Y         Z
A -1.752179  0.328465 -0.547127 -0.136217
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
D -1.086823  0.824722  2.166121 -0.643178
E  0.200822 -0.253019  0.097659  0.744367

In [60]:
df > 0

W      X      Y      Z
A  False   True  False  False
B   True   True   True  False
C   True  False   True   True
D  False   True   True  False
E   True  False   True   True

In [61]:
df[df > 0]

W         X         Y         Z
A       NaN  0.328465       NaN       NaN
B  0.187321  0.590627  0.351814       NaN
C  0.596200       NaN  1.613763  0.286677
D       NaN  0.824722  2.166121       NaN
E  0.200822       NaN  0.097659  0.744367

In [65]:
df['W'] > 0

A    False
B     True
C     True
D    False
E     True
Name: W, dtype: bool

In [63]:
df[df['W'] > 0]

W         X         Y         Z
B  0.187321  0.590627  0.351814 -1.231558
C  0.596200 -1.571288  1.613763  0.286677
E  0.200822 -0.253019  0.097659  0.744367

In [66]:
# rows b,c,e are positive in column W
# but since im doing df[df['W'] > 0], it will display all elements in rows b,c,e

In [67]:
# what if I only want the values in column W that are positive?

B    0.187321
C    0.596200
E    0.200822
Name: W, dtype: float64

In [69]:
states = ['AL','AK','AR','AK','CA']

In [71]:
df['States'] = states

In [73]:
df.set_index('States')

W         X         Y         Z
States                                        
AL     -1.752179  0.328465 -0.547127 -0.136217
AK      0.187321  0.590627  0.351814 -1.231558
AR      0.596200 -1.571288  1.613763  0.286677
AK     -1.086823  0.824722  2.166121 -0.643178
CA      0.200822 -0.253019  0.097659  0.744367

In [74]:
outside = ['G1','G1','G1','G2','G2','G2']

In [75]:
inside = [1,2,3,1,2,3]

In [76]:
hier_index = list(zip(outside,inside))

In [77]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [78]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [79]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [81]:
df = pd.DataFrame(np.random.randn(6,3),hier_index,['A','B','C'])

In [82]:
df

A         B         C
G1 1 -1.851006 -0.500144  0.308458
   2  1.476642 -1.156074 -1.114649
   3 -0.268793 -0.812865 -0.444877
G2 1 -0.975576 -0.325993  0.364594
   2 -0.953749 -0.806393  0.515343
   3  1.354062  0.411354 -1.524613

In [83]:
df['A']

G1  1   -1.851006
    2    1.476642
    3   -0.268793
G2  1   -0.975576
    2   -0.953749
    3    1.354062
Name: A, dtype: float64

In [84]:
type(df['A'])

pandas.core.series.Series

In [85]:
df.loc['G1']

A         B         C
1 -1.851006 -0.500144  0.308458
2  1.476642 -1.156074 -1.114649
3 -0.268793 -0.812865 -0.444877

In [86]:
df.loc['G1']['A']

1   -1.851006
2    1.476642
3   -0.268793
Name: A, dtype: float64

In [87]:
df.loc['G1'].loc[1]

A   -1.851006
B   -0.500144
C    0.308458
Name: 1, dtype: float64

In [88]:
df.loc['G1'].loc[1]['B']

-0.5001436840752488

In [ ]:
df.index.names = 